### ISSUE TITLE
count bits set attribution

### ISSUE THREAD

**Issue by xoorath** [AlexSabourinDev/cpp-utility#7]
> include/utility/BitManipulations.h

If you learned the `v &= v-1;` trick from me, you could give street cred from where I learned it:

It's the Brian Kernighan method of counting bits, apparently.
https://graphics.stanford.edu/~seander/bithacks.html#CountBitsSetKernighan

**Comment by AlexSabourinDev** [comment]
Added attribution as part of the comment. Also added you as the person I got it from.
